version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - DB_HOST= mysql
      - DB_USER= root
      - DB_PASSWORD= root
      - DB_NAME= DevOps
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: DevOps
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
